### ISSUE TITLE
Support padding in addition to cropping

### ISSUE THREAD

**Issue by scottsb** [madzadev/cropper#1]
It would be awesome if this supported padding out an image to the specified aspect ratio/dimensions in addition to cropping it. Platforms like Twitter will size a posted image to fill the frame, cropping off anything outside it. You avoid this by posting the right aspect ratio, but sometimes, such as with an odd-sized screenshot, cropping would remove key content. Instead, the only solution to avoid being cropped in the timeline is to pad out the smaller dimension with blank space (ideally a selectable color).

**Comment by madzadev** [comment]
Thanks for the suggestion, the core Cropper functionality actually supports this.
I might deploy it to prod at some point.
